[build]
  publish = "."

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/photos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/affiches/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
